package com.netsys.gd;

import com.netsys.dao.KhachHangDao;
import com.netsys.entity.khachhang;
import com.netsys.utlis.Auth;
import com.netsys.utlis.TBBOX;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


/**
 *
 * @author ADMIN
 */
public class QLKH extends javax.swing.JDialog {
private int current;
private KhachHangDao dao=new KhachHangDao();
private List<khachhang> Listkh=dao.selectAll();
    public QLKH(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        init();
        xetuser();
    }
  void xetuser(){
     if(Auth.isManager()){
         
     }
     else
     {
     butsua.setEnabled(false);
     butxoa.setEnabled(false);
     f.setEnabled(false);
     ff.setEnabled(false);
     n.setEnabled(false);
     nn.setEnabled(false);
 }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmakh = new javax.swing.JTextField();
        txttenkh = new javax.swing.JTextField();
        txttienconlai = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        butthem = new javax.swing.JButton();
        butsua = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butlammoi = new javax.swing.JButton();
        f = new javax.swing.JButton();
        ff = new javax.swing.JButton();
        n = new javax.swing.JButton();
        nn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkh = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblkhnt = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmakhnt = new javax.swing.JTextField();
        txttenkhnt = new javax.swing.JTextField();
        txtstn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txttcl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmakhtk = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Quản lý khách hàng");

        jLabel1.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        jLabel1.setText("Mã khách hàng:");

        jLabel3.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        jLabel3.setText("Tên khách hàng:");

        jLabel5.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        jLabel5.setText("Số điện thoại :");

        jLabel6.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        jLabel6.setText("Tiền Còn Lại:");

        butthem.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butsua.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        butsua.setText("Sửa");
        butsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsuaActionPerformed(evt);
            }
        });

        butxoa.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        butxoa.setText("Xóa");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        butlammoi.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        butlammoi.setText("Làm mới");
        butlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butlammoiActionPerformed(evt);
            }
        });

        f.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        f.setText("<");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        ff.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        ff.setText(" <<");
        ff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        n.setText(" >>");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        nn.setFont(new java.awt.Font("Source Han Sans CN Bold", 1, 14)); // NOI18N
        nn.setText(" >");
        nn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnActionPerformed(evt);
            }
        });

        tblkh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Tiền Còn Lại", "Số Điện Thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblkh);
        if (tblkh.getColumnModel().getColumnCount() > 0) {
            tblkh.getColumnModel().getColumn(0).setResizable(false);
            tblkh.getColumnModel().getColumn(1).setResizable(false);
            tblkh.getColumnModel().getColumn(2).setResizable(false);
            tblkh.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttienconlai, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(butthem)
                                .addGap(37, 37, 37)
                                .addComponent(butsua)
                                .addGap(40, 40, 40)
                                .addComponent(butxoa)
                                .addGap(37, 37, 37)
                                .addComponent(butlammoi)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ff, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(nn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txttienconlai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butthem)
                            .addComponent(butsua)
                            .addComponent(butxoa)
                            .addComponent(butlammoi)
                            .addComponent(f)
                            .addComponent(ff)
                            .addComponent(n)
                            .addComponent(nn))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin khách hàng", jPanel1);

        tblkhnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Tiền Còn Lại", "Số Điện Thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblkhnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhntMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblkhnt);
        if (tblkhnt.getColumnModel().getColumnCount() > 0) {
            tblkhnt.getColumnModel().getColumn(0).setResizable(false);
            tblkhnt.getColumnModel().getColumn(1).setResizable(false);
            tblkhnt.getColumnModel().getColumn(2).setResizable(false);
            tblkhnt.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã KH");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tiền Còn Lại:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số Tiền Nạp");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("NẠP TIỀN");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/netsys/icon_app/Accept.png"))); // NOI18N
        jButton1.setText("Nạp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/netsys/icon_app/Refresh.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Tên KH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttenkhnt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtmakhnt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtstn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttcl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel9)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmakhnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(txttenkhnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mã KH:");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/netsys/icon_app/Search.png"))); // NOI18N
        jButton3.setText("Seach");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmakhtk, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmakhtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Nạp Tiền Tài Khoản", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
      if(TBBOX.confirm(this, "Bạn Có Muốn Thêm")){
           if(kttt()){
           them();
       }
      }
    }//GEN-LAST:event_butthemActionPerformed

    private void butsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsuaActionPerformed
       if(TBBOX.confirm(this,"Bạn có Muốn Sửa")){
           if(kttt()){
           sua();
       }
       }
    }//GEN-LAST:event_butsuaActionPerformed

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
       if(TBBOX.confirm(this, "Bạn Có Muốn Xóa")){
           if(kttt()){
           xoa();
       }
       }
    }//GEN-LAST:event_butxoaActionPerformed

    private void butlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butlammoiActionPerformed
       if(TBBOX.confirm(this,"Bạn Chắc Chắn Clear")){
           clear();
       }
    }//GEN-LAST:event_butlammoiActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
      if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        else{
            current=0;
            display(current);
        }
    }//GEN-LAST:event_fActionPerformed

    private void ffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        if(current==0){
            JOptionPane.showMessageDialog(this,"Đang ở đầu danh sách!");
            return;
        }
        current--;
        display(current);
    }//GEN-LAST:event_ffActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
         if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        if(current==Listkh.size()-1){
            JOptionPane.showMessageDialog(this,"Đang cuối danh sách!");
            return;
        }
        current++;
        display(current);
    }//GEN-LAST:event_nActionPerformed

    private void nnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        current=Listkh.size()-1;
        display(current);
    }//GEN-LAST:event_nnActionPerformed

    private void tblkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhMouseClicked
       Listkh=dao.selectAll();
        display(tblkh.getSelectedRow());
    }//GEN-LAST:event_tblkhMouseClicked

    private void tblkhntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhntMouseClicked
        Listkh=dao.selectAll();
        display2(tblkhnt.getSelectedRow());
    }//GEN-LAST:event_tblkhntMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(TBBOX.confirm(this, "chắn chắn clear")){
            clear2();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       filltable();
       filltable2();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(TBBOX.confirm(this, "chắn Chắn tìm")){
            if(txtmakhtk.getText().equals("")){
                TBBOX.alert(this, "bạn cần nhập mã cần tìm");
            }
            else{
                timkiem();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(TBBOX.confirm(this, "Chắn Chắn Nạp")){
           if(ktttnt()){
               naptien();
               filltable();
               filltable2();
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLKH dialog = new QLKH(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butlammoi;
    private javax.swing.JButton butsua;
    private javax.swing.JButton butthem;
    private javax.swing.JButton butxoa;
    private javax.swing.JButton f;
    private javax.swing.JButton ff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton n;
    private javax.swing.JButton nn;
    private javax.swing.JTable tblkh;
    private javax.swing.JTable tblkhnt;
    private javax.swing.JTextField txtmakh;
    private javax.swing.JTextField txtmakhnt;
    private javax.swing.JTextField txtmakhtk;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtstn;
    private javax.swing.JTextField txttcl;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JTextField txttenkhnt;
    private javax.swing.JTextField txttienconlai;
    // End of variables declaration//GEN-END:variables

    private void init() {
     filltable();
    }

    private void filltable() {
        DefaultTableModel model=(DefaultTableModel) tblkh.getModel();
        model.setRowCount(0);
        try {
            List<khachhang> list=dao.selectAll();
            for(khachhang kh:list){
                Object[] row={kh.getMakh(),kh.getTenkh(),kh.getTienconlai(),kh.getSdt()};
                System.out.println(kh.getSdt());
                model.addRow(row);
            }
        } catch (Exception e) {
            TBBOX.alert(this,"Lỗi Truy Vấn");
        }
    }
    private void filltable2(){
        DefaultTableModel model=(DefaultTableModel) tblkhnt.getModel();
        model.setRowCount(0);
        try {
            List<khachhang> list=dao.selectAll();
            for(khachhang kh:list){
                Object[] row={kh.getMakh(),kh.getTenkh(),kh.getTienconlai(),kh.getSdt()};
                System.out.println(kh.getSdt());
                model.addRow(row);
            }
        } catch (Exception e) {
            TBBOX.alert(this,"Lỗi Truy Vấn");
        }
    }
    private void display2(int i){
        khachhang kh=Listkh.get(i);
        txtmakhnt.setText(kh.getMakh());
        txttenkhnt.setText(kh.getTenkh());
        txttcl.setText(kh.getTienconlai().toString());
        txtstn.setText("");
    }
   void clear2(){
        txtmakhnt.setText("");
        txttenkhnt.setText("");
        txttcl.setText("");
        txtstn.setText("");
    }
    private void display(int i){
        khachhang kh=Listkh.get(i);
        txtmakh.setText(kh.getMakh());
        txttenkh.setText(kh.getTenkh());
        txttienconlai.setText(kh.getTienconlai().toString());
        txtsdt.setText(kh.getSdt());
    }
    private boolean ktList(){
        if(Listkh.size()<1){
            return true;
        }
        else{
            return false;
        }
    }
    private boolean kttt(){
        if(txtmakh.getText().equals("")||txtmakh.getText()==null){
            TBBOX.alert(this,"thông tin không được trống");
            txtmakh.requestFocus();
            return false;
        }
        else if(txttenkh.getText().equals("") || txttenkh.getText()==null){
            TBBOX.alert(this,"thông tin không được trống");
            txttenkh.requestFocus();
            return false;
        }
        else if(txttienconlai.getText().equals("") || txttienconlai.getText()==null){
            TBBOX.alert(this,"thông tin không được để trống");
            txttienconlai.requestFocus();
            return false;
        }
        return true;
    }
    private void them(){
        khachhang kh=new khachhang();
        kh.setMakh(txtmakh.getText());
        kh.setTenkh(txttenkh.getText());
        kh.setTienconlai(Double.parseDouble(txttienconlai.getText()));
        kh.setSdt(txtsdt.getText());
        try {
            khachhang a=dao.selectByid(txtmakh.getText());
            if(a!=null){
                TBBOX.alert(this, "Khách Hàng Đã Tồn Tại Trong Hệ Thống Vô lòng Cập Nhật Hoặc Nhập Lại TT");
            }
            else{
                dao.insert(kh);
                TBBOX.alert(this,"thêm Thành Công");   
                clear();
                filltable();
                Listkh=dao.selectAll();
            }
        } catch (Exception e) {
            TBBOX.alert(this,"Đã Xãy Ra Lỗi");
            System.out.println(e);
        }
    }

    private void clear() {
        txtmakh.setText("");
        txttenkh.setText("");
        txtsdt.setText("");
        txttienconlai.setText("");
    }
    private void sua(){
          khachhang kh=new khachhang();
        kh.setMakh(txtmakh.getText());
        kh.setTenkh(txttenkh.getText());
        kh.setTienconlai(Double.parseDouble(txttienconlai.getText()));
        kh.setSdt(txtsdt.getText());
        try {
            khachhang a=dao.selectByid(txtmakh.getText());
            if(a!=null){
                 dao.update(kh);
                TBBOX.alert(this,"Cập Nhật Thành Công");   
                clear();
                filltable();
                Listkh=dao.selectAll();
              
            }
            else{
                 TBBOX.alert(this, "Khách Hàng Không Tồn Tại Trong Hệ Thống Vô lòng Thêm Hoặc Nhập Lại TT");
            }
        } catch (Exception e) {
            TBBOX.alert(this,"Đã Xãy Ra Lỗi");
            System.out.println(e);
        }
    }
    private void xoa(){
        try {
            khachhang a=dao.selectByid(txtmakh.getText());
            if(a!=null){
                dao.delete(a.getMakh());
                TBBOX.alert(this,"Xóa Thành Công");
                clear();
                filltable();
                Listkh=dao.selectAll();
            }
            else{
                TBBOX.alert(this,"Khách Hàng Không Tồn Tại");
            }
        } catch (Exception e) {
            TBBOX.alert(this, "đã Xãy Ra Lỗi");
            System.out.println(e);
        }
    }
    private void timkiem(){
        khachhang kh=dao.selectByid(txtmakhtk.getText());
        if(kh!=null){
            txtmakhnt.setText(kh.getMakh());
            txttenkhnt.setText(kh.getTenkh());
            txttcl.setText(kh.getTienconlai().toString());
            txtstn.setText("");
        }
    }
    private boolean ktttnt(){
       if(txtmakhnt.getText().equals("")||txtmakhnt.getText()==null){
            TBBOX.alert(this,"thông tin không được trống");
            txtmakhnt.requestFocus();
            return false;
        }
        else if(txttenkhnt.getText().equals("") || txttenkhnt.getText()==null){
            TBBOX.alert(this,"thông tin không được trống");
            txttenkhnt.requestFocus();
            return false;
        }
        else if(txttcl.getText().equals("") || txttcl.getText()==null){
            TBBOX.alert(this,"thông tin không được để trống");
            txttcl.requestFocus();
            return false;
        }
         else if(txtstn.getText().equals("") || txtstn.getText()==null){
            TBBOX.alert(this,"thông tin không được để trống");
            txtstn.requestFocus();
            return false;
        }
        return true;
    }
    private void naptien(){
        khachhang kh=dao.selectByid(txtmakhnt.getText());
        if(kh!=null){
            kh.setTienconlai(kh.getTienconlai()+Double.parseDouble(txtstn.getText()));
            dao.update(kh);
            TBBOX.alert(this, "Nạp Thành Công");
        }
        else{
            TBBOX.alert(this, "Thất Bại");
        }
    }
}
