/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.netsys.gd;

import com.netsys.dao.NhanVienDAO;
import com.netsys.entity.nhanVien;
import com.netsys.utlis.TBBOX;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nam
 */
public class QuanLyNVJDialog extends javax.swing.JDialog {
private  int current;
private NhanVienDAO dao=new NhanVienDAO();
private List<nhanVien> Listnv=dao.selectAll();
    public QuanLyNVJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        System.out.println(current);
        initComponents();
        this.setLocationRelativeTo(null);
        init();
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnv = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttennv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbtp = new javax.swing.JRadioButton();
        cbbncv = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        laberhinh = new javax.swing.JLabel();
        butuphinh = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        butthem = new javax.swing.JButton();
        butsua = new javax.swing.JButton();
        butxoa = new javax.swing.JButton();
        butlammoi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnf = new javax.swing.JButton();
        btnff = new javax.swing.JButton();
        btnnn = new javax.swing.JButton();
        btnn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txthinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 657, -1, -1));

        tblnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Tên Đăng Nhập", "Mật khẩu", "Vai Trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnv);
        if (tblnv.getColumnModel().getColumnCount() > 0) {
            tblnv.getColumnModel().getColumn(0).setResizable(false);
            tblnv.getColumnModel().getColumn(1).setResizable(false);
            tblnv.getColumnModel().getColumn(2).setResizable(false);
            tblnv.getColumnModel().getColumn(3).setResizable(false);
            tblnv.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 870, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 540, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/netsys/icon_app/Search.png"))); // NOI18N
        jButton6.setText("Seach");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jTabbedPane1.addTab("Danh Sách", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Mã Nhân Viên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Mật Khẩu:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Chức Vụ:");

        buttonGroup1.add(cbbtp);
        cbbtp.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbbtp.setText("Trưởng Phòng");

        buttonGroup1.add(cbbncv);
        cbbncv.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbbncv.setText("Nhân Viên");

        laberhinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/netsys/rs/anhdaidienmatdinh.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laberhinh)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(laberhinh)
                .addGap(32, 32, 32))
        );

        butuphinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butuphinh.setText("Up Hình");
        butuphinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butuphinhActionPerformed(evt);
            }
        });

        butthem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });
        jPanel7.add(butthem);

        butsua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butsua.setText("Sửa");
        butsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsuaActionPerformed(evt);
            }
        });
        jPanel7.add(butsua);

        butxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butxoa.setText("Xóa");
        jPanel7.add(butxoa);

        butlammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butlammoi.setText("Làm Mới");
        butlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butlammoiActionPerformed(evt);
            }
        });
        jPanel7.add(butlammoi);

        btnf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnf.setText("|<");
        btnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfActionPerformed(evt);
            }
        });
        jPanel8.add(btnf);

        btnff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnff.setText("<<");
        btnff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnffActionPerformed(evt);
            }
        });
        jPanel8.add(btnff);

        btnnn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnn.setText(">>");
        btnnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnnActionPerformed(evt);
            }
        });
        jPanel8.add(btnnn);

        btnn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnn.setText(">|");
        btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnActionPerformed(evt);
            }
        });
        jPanel8.add(btnn);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Số Điện Thoại:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Tên Nhân Viên:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(353, 353, 353))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cbbtp)
                                        .addGap(109, 109, 109)
                                        .addComponent(cbbncv))
                                    .addComponent(txttennv, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmatkhau, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butuphinh, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(txthinh))))
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addComponent(txthinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbtp)
                        .addComponent(cbbncv)
                        .addComponent(butuphinh)))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        else{
            current=0;
            display(current);
        }
    }//GEN-LAST:event_btnfActionPerformed

    private void btnffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnffActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        if(current==0){
            JOptionPane.showMessageDialog(this,"Đang ở đầu danh sách!");
            return;
        }
        current--;
        display(current);
    }//GEN-LAST:event_btnffActionPerformed

    private void btnnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnnActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        if(current==Listnv.size()-1){
            JOptionPane.showMessageDialog(this,"Đang cuối danh sách!");
            return;
        }
        current++;
        display(current);
    }//GEN-LAST:event_btnnnActionPerformed

    private void btnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnActionPerformed
        if(ktList()){
            TBBOX.alert(this,"Chưa có nhân viên nào");
            return;
        }
        current=Listnv.size()-1;
        display(current);
    }//GEN-LAST:event_btnnActionPerformed

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
       if(kttt()){
         them();
         fillTable();
         clear();
         Listnv=dao.selectAll();
     }
    }//GEN-LAST:event_butthemActionPerformed

    private void butsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butsuaActionPerformed

    private void butlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butlammoiActionPerformed
      clear();
    }//GEN-LAST:event_butlammoiActionPerformed

    private void butuphinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butuphinhActionPerformed
          JFileChooser jfc = new JFileChooser("src\\main\\java\\images");
        int result = jfc.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                
                 txthinh.setText(jfc.getSelectedFile().getPath());
                  ImageIcon icon = new ImageIcon(txthinh.getText());
               laberhinh.setIcon(icon);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_butuphinhActionPerformed

    private void tblnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnvMouseClicked
         Listnv=dao.selectAll();
        display(tblnv.getSelectedRow());
    }//GEN-LAST:event_tblnvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyNVJDialog dialog = new QuanLyNVJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf;
    private javax.swing.JButton btnff;
    private javax.swing.JButton btnn;
    private javax.swing.JButton btnnn;
    private javax.swing.JButton butlammoi;
    private javax.swing.JButton butsua;
    private javax.swing.JButton butthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton butuphinh;
    private javax.swing.JButton butxoa;
    private javax.swing.JRadioButton cbbncv;
    private javax.swing.JRadioButton cbbtp;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel laberhinh;
    private javax.swing.JTable tblnv;
    private javax.swing.JTextField txthinh;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables

    private void init() {
        fillTable();
    }

    private void fillTable() {
        DefaultTableModel model=(DefaultTableModel) tblnv.getModel();
        model.setRowCount(0);
        try {
            List<nhanVien> list=dao.selectAll();
            for(nhanVien nv:list){
                Object[] row={nv.getManv(),nv.getTenNV(),nv.getUsername(),nv.getPass(),nv.isRole()?"Trưởng Phòng":"Nhân Viên"};
                model.addRow(row);
            }
        } catch (Exception e) {
            TBBOX.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    void display(int i){
        nhanVien nv=Listnv.get(i);
        txttennv.setText(nv.getTenNV());
        txttendangnhap.setText(nv.getUsername());
        txtmatkhau.setText(nv.getPass());
        txthinh.setText(nv.getHinh());
        if(nv.isRole()){
            cbbtp.setSelected(true);
        }else{
            cbbncv.setSelected(true);
        }
        if(txthinh.getText().equals("") || txthinh.getText()==null){
           laberhinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/anhdaidienmatdinh.jpg")));
       }
       else{
           laberhinh.setIcon(new javax.swing.ImageIcon(txthinh.getText()));
       }
       txtsdt.setText(nv.getSdt());
    }

    private  boolean ktList(){
        if(Listnv.size()<1){
            return true;
        }
        else{
            return false;
        }
    }
    private boolean kttt(){
         if(txttennv.getText().equals("") || txttennv.getText()==null){
        TBBOX.alert(this,"Thông tin không được để trống");
        txttennv.requestFocus();
        return false;
    }
    else if(txttendangnhap.getText().equals("") || txttendangnhap.getText()==null){
         TBBOX.alert(this,"Thông tin không được để trống");
         txttendangnhap.requestFocus();
     return false;
    }
    else if(txtmatkhau.getText().equals("") || txtmatkhau.getText()==null){
         TBBOX.alert(this,"Thông tin không được để trống");
         txtmatkhau.requestFocus();
        return false;
    }
    else if(txtsdt.getText().equals("") || txtsdt.getText()==null){
        TBBOX.alert(this,"Thông tin không được để trống");
         txtsdt.requestFocus();
        return false;
    }
    else{
        return true;
    }
    }
    private void them(){
        nhanVien nv=new nhanVien();
        nv.setTenNV(txttennv.getText());
        nv.setUsername(txttendangnhap.getText());
        nv.setPass(txtmatkhau.getText());
        nv.setRole(cbbtp.isSelected());
        nv.setSdt(txtsdt.getText());
        nv.setHinh(txthinh.getText());
        try {
//            nhanVien a= dao.selectByid(txt.getText());
//            if(a!=null){
//                TBBOX.alert(this,"Nhân Viên Đã tồn tại trong hệ thống vui lòng chọn cập nhật hoặc nhập nv khác");
//            }
//            else{
                dao.insert(nv);
                TBBOX.alert(this,"Thêm Thành Công");
//            }
        } catch (Exception e) {
            TBBOX.alert(this,"ĐÃ Xãy ra lỗi");
        }
    }
    private void clear(){
       txttennv.setText("");
       txttendangnhap.setText("");
       txtmatkhau.setText("");
       buttonGroup1.clearSelection();
       txtsdt.setText("");
    }
    void sua(){
     nhanVien nv=new nhanVien();
        nv.setTenNV(txttennv.getText());
        nv.setUsername(txttendangnhap.getText());
        nv.setPass(txtmatkhau.getText());
        nv.setRole(cbbtp.isSelected());
        nv.setSdt(txtsdt.getText());
        nv.setHinh(txthinh.getText());
        try {
            nhanVien a= dao.selectByid(Listnv.get(tblnv.getSelectedRow()).getManv());
            if(a!=null){
                dao.update(nv);
                TBBOX.alert(this,"sua Thành Công");
               
            }
            else{
                 TBBOX.alert(this,"Nhân Viên Không Tại");
            }
        } catch (Exception e) {
            TBBOX.alert(this,"ĐÃ Xãy ra lỗi");
        }
    
}
     void xoa(){
   
        try {
            nhanVien a= dao.selectByid(Listnv.get(current).getManv());
            if(a!=null){
                 dao.delete(a.getManv());
                TBBOX.alert(this,"Xoa Thành Công");
                
            }
            else{
               TBBOX.alert(this,"Nhân Viên Không Tồn Tại");
            }
        } catch (Exception e) {
            TBBOX.alert(this,"ĐÃ Xãy ra lỗi");
        }
    
}
}
